from __future__ import annotations

import csv
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional

from dotenv import load_dotenv
from google import genai
from google.genai import types
from pydantic import BaseModel, Field, ValidationError

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent
LOCAL_DEMOGRAPHICS_CSV = BASE_DIR / "data" / "demographics_sample.csv"


Category = Literal[
    "roads",
    "water",
    "sanitation",
    "health",
    "education",
    "safety",
    "electricity",
    "housing",
    "environment",
    "other",
]


class GeoPoint(BaseModel):
    lat: Optional[float] = Field(default=None, ge=-90, le=90)
    lng: Optional[float] = Field(default=None, ge=-180, le=180)


class SubmissionAnalysis(BaseModel):
    """Strict schema used as Gemini structured output."""

    summary: str = Field(description="One sentence citizen-friendly issue summary.")
    category: Category
    urgency_score: int = Field(ge=1, le=10, description="10 means the issue needs immediate action.")
    sentiment: Literal["negative", "neutral", "positive"]
    suggested_department: str
    constituency_priority: str = Field(description="Why this matters for the constituency plan.")
    keywords: List[str] = Field(default_factory=list, max_length=8)
    location_hint: Optional[str] = Field(default=None, description="Named place or landmark mentioned by the citizen.")
    geocode: Optional[GeoPoint] = None
    rationale: str = Field(description="Brief evidence for category and urgency.")


SYSTEM_INSTRUCTION = """
You are an AI assistant for constituency development planning.
Analyze citizen text, photos, and audio submissions. Classify the civic issue,
estimate urgency, and produce only the requested structured output.
Be careful with uncertainty: if the media or text does not provide a precise
location, leave geocode empty and use location_hint instead.
"""


DEFAULT_DEMOGRAPHICS = [
    {
        "ward_id": "unknown",
        "ward_name": "Unknown ward",
        "population": 0,
        "households": 0,
        "vulnerability_index": 0,
        "water_access_pct": None,
        "sanitation_access_pct": None,
        "health_facility_count": None,
    }
]


def get_client() -> genai.Client:
    """
    Local hackathon demo Gemini client.

    This intentionally uses only the Gemini Developer API key from `.env`.
    """

    return genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))


def _media_part(media: Dict[str, Any]) -> types.Part:
    mime_type = media.get("mime_type") or "application/octet-stream"
    return types.Part.from_bytes(data=media["bytes"], mime_type=mime_type)


def _coerce_analysis(response: Any) -> Dict[str, Any]:
    parsed = getattr(response, "parsed", None)
    if isinstance(parsed, SubmissionAnalysis):
        return parsed.model_dump(mode="json")
    if isinstance(parsed, dict):
        return SubmissionAnalysis.model_validate(parsed).model_dump(mode="json")

    text = getattr(response, "text", None) or ""
    try:
        return SubmissionAnalysis.model_validate_json(text).model_dump(mode="json")
    except ValidationError:
        return SubmissionAnalysis.model_validate(json.loads(text)).model_dump(mode="json")


def _local_fallback_analysis(text: str) -> Dict[str, Any]:
    lowered = text.lower()
    if any(word in lowered for word in ["water", "pipeline", "tap", "drain"]):
        category: Category = "water"
    elif any(word in lowered for word in ["road", "pothole", "traffic", "bridge"]):
        category = "roads"
    elif any(word in lowered for word in ["school", "teacher", "classroom"]):
        category = "education"
    elif any(word in lowered for word in ["hospital", "clinic", "doctor", "health"]):
        category = "health"
    else:
        category = "other"

    urgent_words = ["urgent", "danger", "accident", "flood", "sewage", "blocked", "emergency"]
    urgency = 8 if any(word in lowered for word in urgent_words) else 5
    summary = text.strip()[:180] if text.strip() else "Citizen submitted a media-only issue."

    return SubmissionAnalysis(
        summary=summary,
        category=category,
        urgency_score=urgency,
        sentiment="negative" if urgency >= 8 else "neutral",
        suggested_department="Constituency development office",
        constituency_priority="Needs triage against demographic vulnerability and repeated demand.",
        keywords=[category, "citizen-report"],
        location_hint=None,
        geocode=None,
        rationale="Generated by local fallback because Gemini was unavailable.",
    ).model_dump(mode="json")


def analyze_submission(
    text: str = "",
    media: Optional[List[Dict[str, Any]]] = None,
    demographics_context: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """
    Analyze text, image, and audio submissions with Gemini 2.5.

    Media entries should be dictionaries like:
    {"bytes": b"...", "mime_type": "image/jpeg", "path": "data/uploads/file.jpg"}

    Local upload bytes are sent inline to Gemini so the offline demo has no
    bucket dependency.
    """

    media = media or []
    demographics_context = demographics_context or []
    model = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

    prompt = f"""
Citizen submission text:
{text or "[No typed text. Analyze the attached media/audio.]"}

Relevant demographic context:
{json.dumps(demographics_context[:5], ensure_ascii=True)}

Return a structured civic issue analysis following the schema exactly.
"""

    parts: List[types.Part] = [types.Part.from_text(text=prompt)]
    parts.extend(_media_part(item) for item in media if item.get("bytes"))

    try:
        client = get_client()
        response = client.models.generate_content(
            model=model,
            contents=[types.Content(role="user", parts=parts)],
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                temperature=0.2,
                response_mime_type="application/json",
                response_schema=SubmissionAnalysis,
            ),
        )
        return _coerce_analysis(response)
    except Exception:
        if os.getenv("ENABLE_LOCAL_AI_FALLBACK", "false").lower() == "true":
            return _local_fallback_analysis(text)
        raise


def _load_demographics_csv(csv_path: Path) -> List[Dict[str, Any]]:
    if not csv_path.exists():
        return DEFAULT_DEMOGRAPHICS

    with csv_path.open("r", encoding="utf-8-sig", newline="") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def load_demographics() -> Dict[str, Any]:
    """
    Load constituency demographics strictly from the local CSV.

    The offline demo must never attempt BigQuery or any Google Cloud connection,
    so this uses only backend/data/demographics_sample.csv.
    """

    return {
        "source": "csv_local",
        "path": str(LOCAL_DEMOGRAPHICS_CSV),
        "rows": _load_demographics_csv(LOCAL_DEMOGRAPHICS_CSV),
    }


def fetch_demographics_from_bigquery(
    constituency_id: Optional[str] = None,
    fallback_csv_path: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Compatibility wrapper for the old public-data function name.

    The parameters are accepted so existing main.py calls keep working, but all
    demographic data comes strictly from backend/data/demographics_sample.csv.
    """

    del constituency_id, fallback_csv_path
    return load_demographics()
